"""
Django settings for Djangoshop project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(_x+%_87#nupzd1h1a2^3^z95h#y_rf)(jv7h#k1dg1mbvytqb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Shopapp',
    'Buyerapp',
    'ckeditor',
    'djcelery',
    'rest_framework',
    'ckeditor_uploader'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Djangoshop.middleware.MiddlewareTest',
]

ROOT_URLCONF = 'Djangoshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Djangoshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR,'static'),
)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'static')


# 上传图片用的模块
CKEDITOR_UPLOAD_PATH = 'static/upload'
CKEDITOR_IMAGE_BACKED = 'pillow'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES':[ #权限
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],

    'DEFAULT_RENDERER_CLASSES':( # 返回自定义内容
        'utils.rendererresponse.CustomRenderer',
    ),
    'DEFAULT_FILTER_BACKENDS':(
        'django_filters.rest_framework.DjangoFilterBackend',# django_filter自带的查询过滤器

    ),

    'DEFAULT_PAGINATION_CLASS':'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE':5, # 分页

}

# 当前项目的静态文件目录
# STATIC_ROOT =  os.path.join(BASE_DIR,'static')


# Django一如既往的对发送邮件也进行了封装
# 发送邮件采用SMTP服务
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_USE_TLS = False # 使用tls方式

EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = '1453187816@qq.com'
EMAIL_HOST_PASSWORD = 'sjdoyeqsvlzmghac'
DEFAULT_FROM_EMAIL = '1453187816@qq.com'



# celery 配置
import djcelery #导入django_celery模块
djcelery.setup_loader() #进行模块加载
BROKER_URL = 'redis://127.0.0.1:6379/1'#任务容器地址，Redis数据库地址
CELERY_IMPORTS = ('CeleryTask.tasks')#具体的任务文件
CELERY_TIMEZONE = 'Asia/Shanghai'#celery时区
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'#celery处理器，固定

# celery 的定时器

from celery.schedules import crontab
from celery.schedules import timedelta

CELERYBEAT_SCHEDULE = { # 定时器策略
    u'测试定时器1':{ # 每隔30s运行一次
        'task':'CeleryTask.tasks.taskExample',
        'schedule':timedelta(seconds=30),
        'args':(),
    },
    u'钉钉': {  # 每隔3s运行一次
        'task': 'CeleryTask.tasks.dingTalk',
        #'schedule': crontab(minute='*/1'),
        'schedule':timedelta(seconds=3),
        'args': (),
    },
}




