# Generated by Django 2.2.1 on 2019-07-29 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buyerapp', '0002_auto_20190725_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=32, verbose_name='订单编号')),
                ('order_count', models.IntegerField(verbose_name='商品数量')),
                ('order_price', models.FloatField(verbose_name='订单总价')),
                ('order_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyerapp.Address', verbose_name='订单地址')),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyerapp.Buyer', verbose_name='订单用户')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Goods_id', models.IntegerField(verbose_name='商品id')),
                ('Goods_name', models.CharField(max_length=32, verbose_name='商品名称')),
                ('Goods_price', models.FloatField(verbose_name='商品价格')),
                ('Goods_number', models.IntegerField(verbose_name='商品购买数量')),
                ('Goods_total', models.FloatField(verbose_name='商品总价')),
                ('Goods_store', models.IntegerField(verbose_name='店铺ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyerapp.Order', verbose_name='订单编号（多对一）')),
            ],
        ),
    ]
