# Generated by Django 2.2.1 on 2019-07-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyerapp', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='goods_image',
            field=models.ImageField(default=1, upload_to='', verbose_name='商品图片'),
            preserve_default=False,
        ),
    ]
