# Generated by Django 2.2.1 on 2019-07-25 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopapp', '0002_goods_goods_under'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='goods_under',
            new_name='goods_state',
        ),
    ]
