# Generated by Django 2.2.1 on 2019-07-25 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shopapp', '0003_auto_20190725_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='类型名称')),
                ('description', models.TextField(verbose_name='类型描述')),
                ('picture', models.ImageField(upload_to='buyer/images', verbose_name='类型图片')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Shopapp.GoodsType', verbose_name='商品类型'),
            preserve_default=False,
        ),
    ]
